Resources:
  Webserver1:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceType: t2.micro
  EC2EIPW0T2:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref Webserver1
  Webserver2:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceType: t2.micro
  EC2EIP4WI3V:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref Webserver2